-- ============================================================================
-- MIG-132 · Stock pronta entrega RIMEC — tabla unificada
-- Un CSV (sdrm####) → una tabla; depósito = columna deposito_codigo (D1|DEP2|D3)
-- Precio LPN en guaraníes enteros (sin ÷1000)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.stock_pronta_entrega_rimec (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  deposito_codigo         text NOT NULL
    CHECK (deposito_codigo IN ('D1', 'DEP2', 'D3')),
  almacen_id              bigint NOT NULL DEFAULT 4,

  codigo_barras           text NOT NULL,
  cod_art_proveedor       text,
  cod_grupo               text,

  proveedor_id            bigint NOT NULL,
  tipo_v2_id              smallint NOT NULL CHECK (tipo_v2_id IN (1, 2)),

  linea_id                bigint REFERENCES public.linea (id),
  referencia_id           bigint REFERENCES public.referencia (id),
  material_id             bigint REFERENCES public.material (id),
  color_id                bigint REFERENCES public.color (id),

  linea_codigo_proveedor  bigint,
  referencia_codigo_proveedor bigint,
  excel_material_code     text,
  excel_color_code        text,
  grada                   text NOT NULL DEFAULT '',

  cantidad                numeric(14, 3) NOT NULL CHECK (cantidad > 0),
  cantidad_importada      numeric(14, 3),

  precio_unitario_gs      bigint NOT NULL CHECK (precio_unitario_gs > 0),
  monto_gs                bigint GENERATED ALWAYS AS (
    ROUND(cantidad * precio_unitario_gs)::bigint
  ) STORED,

  batch_label             text NOT NULL,
  archivo_origen          text,
  origen_holding          text NOT NULL DEFAULT 'RIMEC_CSV_SDRM',
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uq_stock_pe_rimec_dep_barra UNIQUE (deposito_codigo, codigo_barras)
);

COMMENT ON TABLE public.stock_pronta_entrega_rimec IS
  'Stock pronta entrega importadora RIMEC · un CSV alimenta D1+DEP2+D3 · precio en Gs';

COMMENT ON COLUMN public.stock_pronta_entrega_rimec.deposito_codigo IS
  'S00_D1→D1 · S00_DEP2→DEP2 · S00_D3→D3 (columnas POS legacy sdrm)';

COMMENT ON COLUMN public.stock_pronta_entrega_rimec.precio_unitario_gs IS
  'LPN del CSV en guaraníes · valor directo sin ÷1000';

COMMENT ON COLUMN public.stock_pronta_entrega_rimec.cantidad IS
  'Unidades POS (pares/cajas) · admite 0.5 media caja';

CREATE INDEX IF NOT EXISTS idx_stock_pe_rimec_deposito
  ON public.stock_pronta_entrega_rimec (deposito_codigo);

CREATE INDEX IF NOT EXISTS idx_stock_pe_rimec_pilares
  ON public.stock_pronta_entrega_rimec (linea_id, referencia_id, material_id, color_id)
  WHERE linea_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_stock_pe_rimec_batch
  ON public.stock_pronta_entrega_rimec (batch_label);

CREATE INDEX IF NOT EXISTS idx_stock_pe_rimec_proveedor
  ON public.stock_pronta_entrega_rimec (proveedor_id, tipo_v2_id);
