-- MIG-161 · Dimensión comercial SDRM — COD.GRUPO · LIQUIDACIÓN · filtro Web desde Report
-- Fuente enriquecida: xlsx sdrm#### (RAMO · MARCA · TIPO0/1/2)

CREATE TABLE IF NOT EXISTS public.sdrm_cod_grupo_dim (
  cod_grupo           text PRIMARY KEY,
  ramo                text NOT NULL,
  marca               text,
  tipo0               text,
  tipo1               text,
  tipo2               text,
  es_liquidacion      boolean NOT NULL DEFAULT false,
  es_promo            boolean NOT NULL DEFAULT false,
  cadena_comercial    text NOT NULL DEFAULT 'REGULAR',
  proveedor_id        bigint,
  articulos_count     integer NOT NULL DEFAULT 0,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.sdrm_cod_grupo_dim IS
  'Dimensión COD.GRUPO SDRM · LIQUIDACIÓN calzado=TIPO1 · confecciones=TIPO2';

CREATE TABLE IF NOT EXISTS public.sdrm_articulo_comercial (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_label         text NOT NULL,
  codigo_barras       text NOT NULL,
  codigo_articulo     text,
  cod_art_proveedor   text,
  cod_grupo           text NOT NULL REFERENCES public.sdrm_cod_grupo_dim (cod_grupo),
  ramo                text NOT NULL,
  marca               text,
  tipo0               text,
  tipo1               text,
  tipo2               text,
  es_liquidacion      boolean NOT NULL DEFAULT false,
  es_promo            boolean NOT NULL DEFAULT false,
  cadena_comercial    text NOT NULL DEFAULT 'REGULAR',
  proveedor_id        bigint,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_sdrm_art_com_batch_barra UNIQUE (batch_label, codigo_barras)
);

CREATE INDEX IF NOT EXISTS idx_sdrm_art_com_batch ON public.sdrm_articulo_comercial (batch_label);
CREATE INDEX IF NOT EXISTS idx_sdrm_art_com_cadena ON public.sdrm_articulo_comercial (cadena_comercial);
CREATE INDEX IF NOT EXISTS idx_sdrm_cod_grupo_cadena ON public.sdrm_cod_grupo_dim (cadena_comercial);

COMMENT ON TABLE public.sdrm_articulo_comercial IS
  'Artículo PE por batch+codigo_barras (CODIGO ARTICULO xlsx) · join v_stock_pe_rimec';

-- Parámetro filtro catálogo Web — gobernado desde Report stock PE
CREATE TABLE IF NOT EXISTS public.pe_catalogo_filtro_web (
  batch_label         text PRIMARY KEY,
  cadena_comercial    text,
  pulse_liquidacion   boolean NOT NULL DEFAULT true,
  updated_at          timestamptz NOT NULL DEFAULT now(),
  updated_by          text
);

COMMENT ON TABLE public.pe_catalogo_filtro_web IS
  'Filtro cadena comercial activo en RIMEC Web PE · toggled desde Report';

COMMENT ON COLUMN public.pe_catalogo_filtro_web.cadena_comercial IS
  'NULL=sin filtro · LIQUIDACION=solo liquidación · PROMOCIONAL=…';

CREATE OR REPLACE FUNCTION public.sdrm_resolver_cadena_comercial(
  p_ramo text,
  p_t0 text,
  p_t1 text,
  p_t2 text
) RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_ramo text := upper(btrim(COALESCE(p_ramo, '')));
  v_t0 text := upper(btrim(COALESCE(p_t0, '')));
  v_t1 text := upper(btrim(COALESCE(p_t1, '')));
  v_t2 text := upper(btrim(COALESCE(p_t2, '')));
BEGIN
  IF v_ramo LIKE '%CONF%' THEN
    IF v_t2 LIKE '%LIQUID%' THEN RETURN 'LIQUIDACION'; END IF;
  ELSE
    IF v_t1 LIKE '%LIQUID%' THEN RETURN 'LIQUIDACION'; END IF;
  END IF;
  IF v_t0 LIKE '%PROM%' OR v_t1 LIKE '%PROM%' OR v_t2 LIKE '%PROM%' THEN
    RETURN 'PROMOCIONAL';
  END IF;
  RETURN 'REGULAR';
END;
$$;
