-- ============================================================================
-- MIG-170 · PP abierto — import proforma sin PP cerrado (Herramienta reposición)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pp_abierto_import (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factura_nro text NOT NULL,
  factura_fecha date,
  archivo_nombre text,
  total_filas integer NOT NULL DEFAULT 0,
  total_pares integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pp_abierto_import_fila (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_id bigint NOT NULL REFERENCES public.pp_abierto_import(id) ON DELETE CASCADE,
  item_nro integer,
  linea_codigo text NOT NULL,
  referencia_codigo text NOT NULL,
  material_code text NOT NULL,
  color_code text NOT NULL,
  descp_material text,
  descp_color text,
  marca text,
  style_code text,
  boxes integer NOT NULL DEFAULT 0,
  pares integer NOT NULL DEFAULT 0,
  unit_fob numeric(14, 4),
  CONSTRAINT uq_pp_abierto_fila_mol UNIQUE (
    import_id,
    linea_codigo,
    referencia_codigo,
    material_code,
    color_code
  )
);

CREATE INDEX IF NOT EXISTS idx_pp_abierto_import_activo
  ON public.pp_abierto_import (activo)
  WHERE activo = true;

CREATE INDEX IF NOT EXISTS idx_pp_abierto_fila_import
  ON public.pp_abierto_import_fila (import_id);

COMMENT ON TABLE public.pp_abierto_import IS
  'Cabecera proforma PP abierto — herramienta reposición AM';
COMMENT ON TABLE public.pp_abierto_import_fila IS
  'Filas molécula L+R+material+color · pares factura proforma abierta';
