-- MIG-171 · Tablas de traducción COD.GRUPO (dígitos Carlos → pilares Nexus)
-- Fuente canónica runtime: report/src/lib/pilares/cod-grupo-decode.ts

CREATE TABLE IF NOT EXISTS public.grupo_digito_marca (
  codigo_2            text PRIMARY KEY,
  id_marca            integer NOT NULL,
  label_canonico      text NOT NULL,
  ramo                text NOT NULL CHECK (ramo IN ('CALZADOS', 'CONFECCIONES')),
  created_at          timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.grupo_digito_marca IS
  'COD.GRUPO dígitos 01-02 → marca_v2.id_marca (Carlos)';

CREATE TABLE IF NOT EXISTS public.grupo_digito_mapa (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ramo                text NOT NULL CHECK (ramo IN ('CALZADOS', 'CONFECCIONES')),
  posicion            text NOT NULL CHECK (posicion IN ('23', '45', '67')),
  codigo              text NOT NULL,
  destino             text NOT NULL CHECK (destino IN ('genero', 'tipo_1', 'estilo', 'cadena', 'marca')),
  label_canonico      text NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_grupo_digito_mapa UNIQUE (ramo, posicion, codigo, destino)
);

COMMENT ON TABLE public.grupo_digito_mapa IS
  'COD.GRUPO posiciones 23/45/67 → destino pilar (género|tipo_1|estilo|cadena)';

CREATE INDEX IF NOT EXISTS idx_grupo_digito_mapa_ramo ON public.grupo_digito_mapa (ramo, posicion);

-- Seed marcas 01–15
INSERT INTO public.grupo_digito_marca (codigo_2, id_marca, label_canonico, ramo) VALUES
  ('01', 1,  'BEIRA RIO',  'CALZADOS'),
  ('02', 2,  'VIZZANO',    'CALZADOS'),
  ('03', 3,  'MODARE',     'CALZADOS'),
  ('04', 4,  'MOLECA',     'CALZADOS'),
  ('05', 5,  'MOLEKINHA',  'CALZADOS'),
  ('06', 6,  'MOLEKINHO',  'CALZADOS'),
  ('07', 7,  'ACTVITTA',   'CALZADOS'),
  ('08', 8,  'BR SPORT',   'CALZADOS'),
  ('09', 9,  'CHINELO',    'CALZADOS'),
  ('10', 10, 'KYLY',       'CONFECCIONES'),
  ('11', 11, 'MILON',      'CONFECCIONES'),
  ('12', 12, 'AMORA',      'CONFECCIONES'),
  ('13', 13, 'LEMON',      'CONFECCIONES'),
  ('14', 14, 'NANAI',      'CONFECCIONES'),
  ('15', 15, 'PIPA',       'CONFECCIONES')
ON CONFLICT (codigo_2) DO UPDATE SET
  id_marca = EXCLUDED.id_marca,
  label_canonico = EXCLUDED.label_canonico,
  ramo = EXCLUDED.ramo;

-- Seed mapa dígitos · CONFECCIONES
INSERT INTO public.grupo_digito_mapa (ramo, posicion, codigo, destino, label_canonico) VALUES
  ('CONFECCIONES', '23', '01', 'genero', 'NINAS'),
  ('CONFECCIONES', '23', '02', 'genero', 'NINOS'),
  ('CONFECCIONES', '45', '01', 'tipo_1', 'INVIERNO'),
  ('CONFECCIONES', '45', '02', 'tipo_1', 'VERANO'),
  ('CONFECCIONES', '67', '01', 'estilo', 'ACTUAL'),
  ('CONFECCIONES', '67', '02', 'estilo', 'ANTERIOR'),
  ('CONFECCIONES', '67', '03', 'cadena', 'PROMOCIONAL'),
  ('CONFECCIONES', '67', '04', 'cadena', 'LIQUIDACION'),
  -- CALZADOS
  ('CALZADOS', '23', '01', 'tipo_1', 'ABIERTO'),
  ('CALZADOS', '23', '02', 'tipo_1', 'CERRADO'),
  ('CALZADOS', '23', '03', 'tipo_1', 'CARTERAS'),
  ('CALZADOS', '23', '04', 'tipo_1', 'MEDIAS'),
  ('CALZADOS', '23', '05', 'tipo_1', 'PRENDAS'),
  ('CALZADOS', '45', '01', 'cadena', 'REGULAR'),
  ('CALZADOS', '45', '02', 'cadena', 'PROMOCIONAL'),
  ('CALZADOS', '45', '04', 'cadena', 'LIQUIDACION'),
  ('CALZADOS', '67', '00', 'estilo', 'OTROS'),
  ('CALZADOS', '67', '01', 'estilo', 'BOTAS'),
  ('CALZADOS', '67', '90', 'estilo', 'OTROS'),
  ('CALZADOS', '67', '01', 'genero', 'DAMAS'),
  ('CALZADOS', '67', '02', 'genero', 'CABALLEROS')
ON CONFLICT (ramo, posicion, codigo, destino) DO UPDATE SET
  label_canonico = EXCLUDED.label_canonico;
