-- MIG-185 · Descuento comercial dictado PE (por molécula)
-- ≠ comisión D1 (pe_diccionario_cadena.descuento_d1_pct).
-- Clave = batch_label + L + R + mat + color (códigos proveedor).

CREATE TABLE IF NOT EXISTS public.pe_descuento_comercial_molecula (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_label       text NOT NULL DEFAULT '',
  linea_codigo      text NOT NULL,
  referencia_codigo text NOT NULL,
  material_code     text NOT NULL,
  color_code        text NOT NULL,
  descuento_pct     numeric(5, 2) NOT NULL
    CHECK (descuento_pct >= 0 AND descuento_pct <= 100),
  assigned_by       text,
  assigned_at       timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_pe_desc_comercial_mol
    UNIQUE (batch_label, linea_codigo, referencia_codigo, material_code, color_code)
);

CREATE INDEX IF NOT EXISTS idx_pe_desc_comercial_batch
  ON public.pe_descuento_comercial_molecula (batch_label);

CREATE INDEX IF NOT EXISTS idx_pe_desc_comercial_codes
  ON public.pe_descuento_comercial_molecula
  (linea_codigo, referencia_codigo, material_code, color_code);

COMMENT ON TABLE public.pe_descuento_comercial_molecula IS
  'Descuento comercial PE dictado (Report Asignación). No es comisión D1.';

GRANT SELECT ON public.pe_descuento_comercial_molecula TO anon, authenticated, service_role;
GRANT INSERT, UPDATE, DELETE ON public.pe_descuento_comercial_molecula TO service_role;
