-- MIG-186 · Bóveda RIMEC — archivo operativo Facturación PE
-- Soft-archive: no muta factura_interna.estado

CREATE TABLE IF NOT EXISTS public.facturacion_boveda_rimec (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factura_interna_id   bigint NOT NULL
    REFERENCES public.factura_interna (id) ON DELETE CASCADE,
  origen               text NOT NULL DEFAULT 'pronta-entrega',
  archivado_en         timestamptz NOT NULL DEFAULT now(),
  archivado_por        integer NULL,
  nota                 text NULL,
  CONSTRAINT uq_facturacion_boveda_fi UNIQUE (factura_interna_id),
  CONSTRAINT chk_facturacion_boveda_origen
    CHECK (origen IN ('pronta-entrega', 'transito'))
);

CREATE INDEX IF NOT EXISTS idx_facturacion_boveda_origen_fecha
  ON public.facturacion_boveda_rimec (origen, archivado_en DESC);

COMMENT ON TABLE public.facturacion_boveda_rimec IS
  'Bóveda RIMEC — FI archivadas desde Facturación (sale de bandeja viva; estado FI intacto).';

GRANT SELECT ON public.facturacion_boveda_rimec TO anon, authenticated, service_role;
GRANT INSERT, UPDATE, DELETE ON public.facturacion_boveda_rimec TO service_role;
